# Generated by Django 5.0.2 on 2024-02-27 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 17, 29, 10, 691628, tzinfo=datetime.timezone.utc)),
        ),
    ]
