# Generated by Django 5.0.2 on 2024-02-27 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 18, 11, 22, 264036, tzinfo=datetime.timezone.utc)),
        ),
    ]
