# Generated by Django 5.0.2 on 2024-03-04 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 4, 18, 33, 6, 269790, tzinfo=datetime.timezone.utc)),
        ),
    ]
